# Opt in to new cops by default
AllCops:
  Exclude:
    - DerivedData/**/*
    - vendor/**/*
  NewCops: enable

# Allow the Podspec filename to match the project
Naming/FileName:
  Exclude:
    - 'MediaEditor.podspec'
