# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: mac

env:
  IMAGE_ID: xcode-16.4

# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
    - automattic/a8c-ci-toolkit#5.3.1

# This is the default pipeline – it will build and test the library
steps:
  #################
  # Build and Test
  #################
  - label: "🔬 Build and Test"
    key: "test"
    command: |
      install_gems
      bundle exec fastlane ios test
    plugins: *common_plugins
    artifact_paths:
      - .build/logs/*.log
      - .build/derived-data/Logs/**/*.xcactivitylog

  #################
  # Lint
  #################
  - label: "🧹 Lint"
    key: "lint"
    command: |
      install_gems
      bundle exec rubocop
    plugins: *common_plugins
